pwa.settings:
  type: mapping
  label: Settings
  mapping:
    short_name:
      type: string
    start_url:
      type: string
    background_color:
      type: color_hex
    theme_color:
      type: color_hex
    orientation:
      type: string
    display:
      type: string
    serviceworker_cache_version:
      type: integer
    serviceworker_preload:
      type: sequence
      sequence:
        type: string
    serviceworker_cache_exclude:
      type: sequence
      sequence:
        type: string
